sudo: false
dist: trusty
language: node_js
node_js:
  - node
os:
  - osx
  - linux
matrix:
  allow_failures:
    - os: osx
cache:
  directories:
    - ~/.npm
    - ~/.electron
    - ~/.nvm
addons:
  apt:
    packages:
      - xvfb
      - icnsutils
      - graphicsmagick
      - xz-utils
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - export JOBS=max
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - node --version
  - npm --version
install:
  - npm i
script:
  - npm test
after_success:
  - npm dist
