build: off

platform:
  - x64

cache:
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\.npm'

install:
  - ps: Install-Product node 8 x64
  - npm i

test_script:
  - node --version
  - npm --version
  - npm test

on_success:
  - npm run dist

environment:
  GH_TOKEN:
    secure: mtm1UAUZ0tByhVTYD+cTXy530JM6N9D6bE6aXR37EUMW7JzF91LMuqXBjSEzUf7z

