build: off

platform:
  - x64

cache:
  - '%USERPROFILE%\.electron'
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node 7 x64
  - yarn

test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn run test

on_success:
  - yarn run dist

environment:
  GH_TOKEN:
    secure: mtm1UAUZ0tByhVTYD+cTXy530JM6N9D6bE6aXR37EUMW7JzF91LMuqXBjSEzUf7z

